name: Collect

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '42 1 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    container: python:3.11

    steps:
      - uses: actions/checkout@v3

      - name: Checkout collector
        uses: actions/checkout@v3
        with:
          repository: 'szabgab/forem-author-stats'
          path: forem-author-stats
          ref: 'v1'

      - name: install dependencies
        run: |
          pip install -r forem-author-stats/requirements.txt

      - name: Collect Data
        run: |
          python forem-author-stats/collect.py --username szabgab

      - name: Commit new data
        run: |
            GIT_STATUS=$(git status --porcelain)
            echo $GIT_STATUS
            git config --global user.name 'Gabor Szabo'
            git config --global user.email 'gabor@szabgab.com'
            git add data/
            if [ "$GIT_STATUS" != "" ]; then git commit -m "Update collected data"; fi
            if [ "$GIT_STATUS" != "" ]; then git push; fi

