name: Collect

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '42 1 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v3

      - name: Collect Data
        uses: szabgab/forem-author-stats@v1
        with:
          username: szabgab

      - name: Commit new data
        run: |
            GIT_STATUS=$(git status --porcelain)
            echo $GIT_STATUS
            git config --global user.name 'Gabor Szabo'
            git config --global user.email 'gabor@szabgab.com'
            git add data/
            if [ "$GIT_STATUS" != "" ]; then git commit -m "Update collected data"; fi
            if [ "$GIT_STATUS" != "" ]; then git push; fi

